// Build-time only. Lifts the 11 glyphs this dashboard uses out of the vendored
// Aurora bundle's extracted path data, so no icon webfont and no icon package is
// needed at runtime. Regenerate with: npm run icons --workspace @ops-dash/web
import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';

const BUNDLE = '../design_handoff_it_ops_dashboard/aurora/_ds_bundle.js';
const OUT = 'src/components/aurora/icons.generated.ts';

/** designer-facing snake_case name -> Aurora's PascalCase glyph key stem */
const NAMES = {
  monitoring: 'Monitoring',
  space_dashboard: 'SpaceDashboard',
  dns: 'Dns',
  report: 'Report',
  shield: 'Shield',
  computer: 'Computer',
  mail: 'Mail',
  settings: 'Settings',
  task_alt: 'TaskAlt',
  nights_stay: 'NightsStay',
  light_mode: 'LightMode',
};

// Pinned 2026-09-19. This script evals the bundle and its output is rendered
// through dangerouslySetInnerHTML on every page, so a silent swap is a
// code-execution path — at build time on this machine, and as arbitrary markup
// in the browser. The file is vendored, committed and diffable, which is most
// of the defence; the pin is the part that fails loudly rather than shipping.
// If this throws: the bundle changed. Diff it, understand why, then update.
const BUNDLE_SHA256 = '24ca75952a96991537b4361e8292092da9138ac729eb74b00ade05dc317f83b5';

const bundleSource = readFileSync(BUNDLE, 'utf8');
const actual = createHash('sha256').update(bundleSource).digest('hex');
if (actual !== BUNDLE_SHA256) {
  throw new Error(
    `Aurora bundle hash mismatch — refusing to eval it.\n  expected ${BUNDLE_SHA256}\n  actual   ${actual}`,
  );
}

const line = bundleSource
  .split('\n')
  .find((l) => l.startsWith('let __ds_default_components_foundation_icon_data_hdnrqo;'));
if (!line) throw new Error('icon-data line not found in the Aurora bundle');

const start = line.indexOf('={') + 1;
const end = line.lastIndexOf('};}catch{}') + 1;
if (start < 1 || end < 1) throw new Error('could not bracket the icon-data object literal');

// The bundle is vendored, committed and read at build time only — eval is the
// cheapest correct parser for a JS object literal with unquoted keys.
const data = eval(`(${line.slice(start, end)})`);

const entries = Object.entries(NAMES).map(([slug, stem]) => {
  const key = `${stem}WeightRegular`;
  const glyph = data[key];
  if (!glyph) throw new Error(`glyph ${key} is missing from the Aurora bundle`);
  return `  ${slug}: { viewBox: ${JSON.stringify(glyph.viewBox)}, body: ${JSON.stringify(glyph.body)} },`;
});

writeFileSync(
  OUT,
  `// GENERATED by scripts/extract-icons.mjs from design_handoff_it_ops_dashboard/aurora/_ds_bundle.js
// Do not hand-edit. Regenerate with: npm run icons --workspace @ops-dash/web

export type IconName = ${Object.keys(NAMES).map((n) => `'${n}'`).join(' | ')};

export const ICONS: Record<IconName, { viewBox: string; body: string }> = {
${entries.join('\n')}
};
`,
);
console.log(`wrote ${OUT} (${entries.length} glyphs)`);
