import { ageLabel, UNKNOWN_AGE } from './ageLabel.js';

/**
 * The two sentences this app composes from `ageLabel`, in one place.
 *
 * `ageLabel` is deliberately non-directional — it returns a bare magnitude
 * ('14 minutes'), and the caller says what the magnitude means. That is right,
 * and it is why these compositions exist rather than living inside it.
 *
 * They are HERE rather than in a view because five sites were composing them
 * independently and **only one handled `UNKNOWN_AGE`**: `Panel.tsx`'s private
 * `agePhrase`. Everywhere else, an unparseable timestamp rendered
 * 'an unknown age ago' — a sentence no person would write. No fixture reaches
 * it today, because every timestamp is generated by `fixtures/time.ts`; a
 * Milestone 2 vendor payload with a malformed date will.
 *
 * So the rule the hoist exists to enforce: **an unknown age is not an age, and
 * the sentence must change shape rather than interpolate the placeholder.**
 */

/** A past instant: '34 days ago', or 'at an unknown time' when unparseable. */
export function ago(iso: string, now?: number): string {
  const age = ageLabel(iso, now);
  return age === UNKNOWN_AGE ? 'at an unknown time' : `${age} ago`;
}

/** A duration held: '14 minutes old', or 'of unknown age' when unparseable.
 *  This is `Panel.tsx`'s original `agePhrase`, which was the only correct one. */
export function agePhrase(iso: string, now?: number): string {
  const age = ageLabel(iso, now);
  return age === UNKNOWN_AGE ? 'of unknown age' : `${age} old`;
}

/** '+1,102' / '-2' / '0'. A rise is signed, a fall carries its own minus, and
 *  zero is never '+0' — the prototype's own convention. Hoisted with `ago`
 *  because it had the same problem: exported from a view, imported by two
 *  others, owned by nobody as a utility. */
export function signedDelta(n: number): string {
  const formatted = n.toLocaleString('en-US');
  return n > 0 ? `+${formatted}` : formatted;
}

/**
 * A wall-clock stamp that cannot be mistaken for today: '09:41' when the
 * instant falls on today's date, 'Thu 09:41' when it does not.
 *
 * The team ruled once already that "'at 14:30' on a two-day-old acknowledgement
 * reads as today", and applied it to the credit line. This is the same ruling
 * applied to the two places that were missed: the incident hero's
 * `Opened {time}` and every timeline row. Photographing a two-day-old incident
 * for the first time is what exposed them — its timeline rows read 09:41 and
 * 09:43 against a frozen clock of 09:41:02, so the newest entry appeared to be
 * two minutes in the FUTURE.
 *
 * A clock time is kept rather than replaced by a magnitude, because on an
 * incident timeline the ordering and the gaps between entries are the point,
 * and 'two days ago / two days ago / two days ago' loses both.
 */
export function clockStamp(iso: string, now: number = Date.now()): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return 'unknown time';
  const hhmm = `${String(d.getHours()).padStart(2, '0')}:${String(d.getMinutes()).padStart(2, '0')}`;
  const n = new Date(now);
  const sameDay =
    d.getFullYear() === n.getFullYear() && d.getMonth() === n.getMonth() && d.getDate() === n.getDate();
  if (sameDay) return hhmm;
  const day = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'][d.getDay()];
  return `${day} ${hhmm}`;
}
